=== openwebdocs/mdn-bcd-collector/types/report.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "exposure": {
      "type": "string",
      "enum": [
        "ServiceWorker",
        "SharedWorker",
        "Window",
        "Worker",
        "WebAssembly"
      ]
    },

    "feature_name": {
      "type": "string",
      "pattern": "^[a-zA-Z_0-9-$@.]*$",
      "description": "Dot separated identifier path.\n\n@example \"javascript.builtins.Array.at\""
    },

    "result_message": {
      "type": "string",
      "description": "An error message from the browser or from the test framework.\n\n@example \"threw TypeError: Failed to construct 'Notification': Illegal constructor.\"\n@example \"Testing CanvasRenderingContext2D in workers is not yet implemented\"\n@example \"Browser does not support detection methods\""
    },

    "collector_result": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "exposure": {"$ref": "#/definitions/exposure"},
            "message": {"$ref": "#/definitions/result_message"},
            "name": {"$ref": "#/definitions/feature_name"},
            "result": {"type": "boolean"}
          },
          "additionalProperties": false,
          "required": ["exposure", "name", "result"]
        },
        {
          "type": "object",
          "properties": {
            "exposure": {"$ref": "#/definitions/exposure"},
            "message": {"$ref": "#/definitions/result_message"},
            "name": {"$ref": "#/definitions/feature_name"},
            "result": {"type": "null"}
          },
          "additionalProperties": false,
          "required": ["exposure", "message", "name", "result"]
        }
      ]
    }
  },

  "title": "Report",
  "type": "object",
  "properties": {
    "__version": {
      "type": "string",
      "pattern": "^[0-9.]+$",
      "description": "Version of mdn-bcd-collector that collected the report."
    },
    "extensions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "results": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/collector_result"
          }
        }
      },
      "minProperties": 1
    },
    "userAgent": {
      "type": "string",
      "description": "User agent of tested browser."
    },
    "preview": {
      "type": "boolean",
      "description": "Whether the report is from a preview browser (Nightly, Canary, Technical Preview)."
    }
  },
  "required": ["__version", "results", "userAgent"],
  "additionalProperties": false
}

=== openwebdocs/mdn-bcd-collector/unittest/report.test.json
{
  "__version": "1.0.0",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537",
  "extensions": ["extension1", "extension2"],
  "preview": false,
  "results": {
    "http://example.com": [
      {
        "exposure": "Window",
        "name": "javascript.builtins.Array.at",
        "result": true
      },
      {
        "exposure": "ServiceWorker",
        "name": "javascript.builtins.String.includes",
        "result": false,
        "message": "Browser does not support detection methods"
      },
      {
        "exposure": "WebAssembly",
        "name": "javascript.builtins.Math.random",
        "result": null,
        "message": "Testing Math.random in WebAssembly is not yet implemented"
      }
    ]
  }
}
